# Generated by Django 5.2.17 on 2026-08-09 14:01

import django.db.models.deletion
import django_jalali.db.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FittingProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('planned_quantity', models.PositiveIntegerField(default=0, verbose_name='مقدار برنامه\u200cریزی\u200cشده')),
                ('produced_quantity', models.PositiveIntegerField(default=0, verbose_name='مقدار تولیدشده')),
                ('scrap_quantity', models.PositiveIntegerField(default=0, verbose_name='مقدار ضایعات')),
                ('material_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مواد مصرف\u200cشده (kg)')),
                ('material_scrap', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مواد ضایعات\u200cشده (kg)')),
                ('deviation_reason', models.TextField(blank=True, verbose_name='دلیل انحراف')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shot_cycle', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='سیکل تولید یک\u200cضرب (ثانیه)')),
                ('active_cavities', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد حفره فعال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fitting_records', to='catalog.machine')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fitting_records', to='catalog.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productionunit')),
            ],
            options={
                'verbose_name': 'تولید اتصالات',
                'verbose_name_plural': 'تولید روزانه اتصالات',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipeProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('planned_quantity', models.PositiveIntegerField(default=0, verbose_name='مقدار برنامه\u200cریزی\u200cشده')),
                ('produced_quantity', models.PositiveIntegerField(default=0, verbose_name='مقدار تولیدشده')),
                ('scrap_quantity', models.PositiveIntegerField(default=0, verbose_name='مقدار ضایعات')),
                ('material_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مواد مصرف\u200cشده (kg)')),
                ('material_scrap', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مواد ضایعات\u200cشده (kg)')),
                ('deviation_reason', models.TextField(blank=True, verbose_name='دلیل انحراف')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipe_type', models.CharField(max_length=60, verbose_name='نوع محصول')),
                ('size', models.CharField(blank=True, max_length=40, verbose_name='سایز')),
                ('socket_length', models.CharField(blank=True, choices=[('30cm_1s', '۳۰ سانتی یک\u200cسر سوکت'), ('50cm_1s', 'نیم\u200cمتری یک\u200cسر سوکت'), ('100cm_1s', '۱ متری یک\u200cسر سوکت'), ('200cm_1s', '۲ متری یک\u200cسر سوکت'), ('300cm_1s', '۳ متری یک\u200cسر سوکت'), ('50cm_2s', 'نیم\u200cمتری دوسر سوکت'), ('100cm_2s', '۱ متری دوسر سوکت'), ('300cm_2s', '۳ متری دوسر سوکت')], max_length=20, verbose_name='اندازه لوله (سوکت)')),
                ('nominal_pressure', models.CharField(blank=True, max_length=20, verbose_name='فشار اسمی')),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ضخامت')),
                ('thickness_unit', models.CharField(choices=[('mm', 'میلی\u200cمتر'), ('micron', 'میکرون')], default='mm', max_length=10)),
                ('material_grade', models.CharField(blank=True, help_text='PE80 / PE100 / PE32 / PE40', max_length=20, verbose_name='نوع مواد')),
                ('dripper_spec', models.CharField(blank=True, max_length=120, verbose_name='مشخصات دریپر')),
                ('nominal_flow', models.CharField(blank=True, max_length=40, verbose_name='دبی اسمی')),
                ('dripper_spacing', models.PositiveIntegerField(blank=True, null=True, verbose_name='فاصله دریپر (cm)')),
                ('length_meters', models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ تولید (m)')),
                ('color', models.CharField(blank=True, max_length=40, verbose_name='رنگ')),
                ('bling_machine', models.ForeignKey(blank=True, limit_choices_to={'machine_type': 'bling'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bling_records', to='catalog.machine')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipe_records', to='catalog.machine')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipe_records', to='catalog.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productionunit')),
            ],
            options={
                'verbose_name': 'تولید لوله',
                'verbose_name_plural': 'تولید روزانه لوله\u200cها',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStoppage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(default=0, verbose_name='مدت توقف (دقیقه)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح تکمیلی')),
                ('fitting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stoppages', to='production.fittingproduction')),
                ('pipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stoppages', to='production.pipeproduction')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stoppages', to='catalog.stoppagereason')),
            ],
            options={
                'verbose_name': 'توقف',
                'verbose_name_plural': 'توقفات',
            },
        ),
    ]
