# Generated by Django 5.2.17 on 2026-08-09 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_deviationreason_product_unit_weight_grams_and_more'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fittingproduction',
            name='deviation_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.deviationreason', verbose_name='دلیل انحراف'),
        ),
        migrations.AlterField(
            model_name='fittingproduction',
            name='shot_cycle',
            field=models.PositiveIntegerField(default=0, verbose_name='سیکل تولید یک\u200cضرب (ثانیه)'),
        ),
        migrations.AlterField(
            model_name='pipeproduction',
            name='deviation_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.deviationreason', verbose_name='دلیل انحراف'),
        ),
        migrations.AlterField(
            model_name='pipeproduction',
            name='material_grade',
            field=models.CharField(blank=True, choices=[('PE80', 'PE80'), ('PE100', 'PE100'), ('PE32', 'PE32'), ('PE40', 'PE40')], max_length=20, verbose_name='نوع مواد'),
        ),
    ]
