# Generated by Django 5.2.17 on 2026-08-09 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_deviationreason_product_unit_weight_grams_and_more'),
        ('production', '0002_alter_fittingproduction_deviation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fittingproduction',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fitting_records', to='catalog.machine', verbose_name='دستگاه'),
        ),
        migrations.AlterField(
            model_name='fittingproduction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fitting_records', to='catalog.product', verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='fittingproduction',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productionunit', verbose_name='واحد تولیدی'),
        ),
        migrations.AlterField(
            model_name='pipeproduction',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipe_records', to='catalog.machine', verbose_name='خط'),
        ),
        migrations.AlterField(
            model_name='pipeproduction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipe_records', to='catalog.product', verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='pipeproduction',
            name='thickness_unit',
            field=models.CharField(choices=[('mm', 'میلی\u200cمتر'), ('micron', 'میکرون')], default='mm', max_length=10, verbose_name='واحد ضخامت'),
        ),
        migrations.AlterField(
            model_name='pipeproduction',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productionunit', verbose_name='واحد تولیدی'),
        ),
        migrations.AlterField(
            model_name='productionstoppage',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stoppages', to='catalog.stoppagereason', verbose_name='دلیل توقف'),
        ),
    ]
