# Generated by Django 5.2.17 on 2026-08-09 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_deviationreason_product_unit_weight_grams_and_more'),
        ('production', '0003_alter_fittingproduction_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeproduction',
            name='bling_machine',
            field=models.ForeignKey(blank=True, limit_choices_to={'machine_type': 'bling'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bling_records', to='catalog.machine', verbose_name='دستگاه بلینگ'),
        ),
    ]
