# Generated by Django 5.2.17 on 2026-08-10 11:38

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_programchangereason'),
        ('planning', '0003_weeklyplanitem_sequence_weeklyplanitem_uid'),
        ('production', '0004_alter_pipeproduction_bling_machine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting', 'در انتظار تولید'), ('running', 'در حال تولید'), ('temp_stop', 'توقف موقت'), ('finished', 'اتمام تولید')], default='awaiting', max_length=12, verbose_name='وضعیت')),
                ('change_type', models.CharField(blank=True, choices=[('setup', 'راه\u200cاندازی'), ('change', 'تغییر برنامه')], max_length=8, verbose_name='نوع شروع')),
                ('production_type', models.PositiveSmallIntegerField(default=1, verbose_name='نوع تولید')),
                ('start_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع')),
                ('stop_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان/توقف')),
                ('stop_time', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان/توقف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.programchangereason', verbose_name='دلیل تغییر برنامه')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='planning.weeklyplanitem')),
            ],
            options={
                'verbose_name': 'برنامه تولید',
                'verbose_name_plural': 'برنامه\u200cهای تولید',
            },
        ),
        migrations.CreateModel(
            name='ProductionDayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('produced_quantity', models.PositiveIntegerField(default=0, verbose_name='مقدار تولیدشده (ضرب)')),
                ('scrap_quantity', models.PositiveIntegerField(default=0, verbose_name='مقدار ضایعات')),
                ('cycle', models.PositiveIntegerField(default=0, verbose_name='سیکل یک\u200cضرب (ثانیه)')),
                ('active_cavities', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد حفره فعال')),
                ('planned_quantity', models.PositiveIntegerField(default=0, verbose_name='مقدار برنامه\u200cریزی\u200cشده (ضرب)')),
                ('active_seconds', models.PositiveIntegerField(default=0, verbose_name='زمان فعال (ثانیه)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deviation_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.deviationreason', verbose_name='دلیل انحراف')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='production.productionprogram', verbose_name='برنامه تولید')),
            ],
            options={
                'verbose_name': 'آمار تولید روزانه',
                'verbose_name_plural': 'آمار تولید روزانه',
                'ordering': ['date'],
                'unique_together': {('program', 'date')},
            },
        ),
    ]
