# Generated by Django 5.2.17 on 2026-08-10 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_moldoption'),
        ('production', '0005_productionprogram_productiondayentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionprogram',
            name='mold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.moldoption', verbose_name='انتخاب قالب'),
        ),
    ]
