# Generated by Django 5.2.17 on 2026-08-09 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('planning_manager', 'مدیر برنامه\u200cریزی'), ('planning_expert', 'کارشناس برنامه\u200cریزی'), ('planning_clerk', 'کارمند برنامه\u200cریزی'), ('viewer', 'مشاهده\u200cگر')], default='viewer', max_length=32)),
                ('can_edit_others', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
