# Generated by Django 5.2.17 on 2026-08-09 14:01

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_number', models.CharField(max_length=30, unique=True, verbose_name='شماره برنامه')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ برنامه\u200cریزی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تأیید'), ('approved', 'تأییدشده'), ('rejected', 'ردشده')], default='draft', max_length=12)),
                ('alarms', models.TextField(blank=True, verbose_name='هشدارها')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'برنامه هفتگی',
                'verbose_name_plural': 'برنامه\u200cریزی هفتگی',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mold_change_weekday', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز تعویض قالب')),
                ('mold_change_date', django_jalali.db.models.jDateField(verbose_name='تاریخ تعویض قالب')),
                ('active_cavities', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد حفره فعال')),
                ('history_alarm', models.BooleanField(default=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.machine')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planning.weeklyplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productsubgroup')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productionunit')),
            ],
            options={
                'verbose_name': 'قلم برنامه',
                'verbose_name_plural': 'اقلام برنامه',
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='مقدار تولید')),
                ('cycle', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='سیکل تولید (ثانیه)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='planning.weeklyplanitem')),
                ('production_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productiontypeoption')),
            ],
            options={
                'verbose_name': 'ردیف تولید',
                'verbose_name_plural': 'ردیف\u200cهای تولید',
            },
        ),
    ]
