# Generated by Django 5.2.17 on 2026-08-09 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_deviationreason_product_unit_weight_grams_and_more'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyplanitem',
            options={'verbose_name': 'کالای برنامه', 'verbose_name_plural': 'کالاهای برنامه'},
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='status',
            field=models.CharField(choices=[('draft', 'موقت'), ('approved', 'تأییدشده')], default='draft', max_length=12),
        ),
        migrations.AlterField(
            model_name='weeklyplanitem',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.machine', verbose_name='دستگاه'),
        ),
        migrations.AlterField(
            model_name='weeklyplanitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product', verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='weeklyplanitem',
            name='subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productsubgroup', verbose_name='زیرگروه'),
        ),
        migrations.AlterField(
            model_name='weeklyplanitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productionunit', verbose_name='واحد تولیدی'),
        ),
        migrations.AlterField(
            model_name='weeklyplanline',
            name='cycle',
            field=models.PositiveIntegerField(default=0, verbose_name='سیکل تولید (ثانیه)'),
        ),
        migrations.AlterField(
            model_name='weeklyplanline',
            name='production_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productiontypeoption', verbose_name='نوع تولید'),
        ),
    ]
