# Generated by Django 5.2.17 on 2026-08-10 11:38

import planning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_alter_weeklyplanitem_options_alter_weeklyplan_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplanitem',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب روی دستگاه'),
        ),
        migrations.AddField(
            model_name='weeklyplanitem',
            name='uid',
            field=models.CharField(db_index=True, default=planning.models.generate_program_uid, editable=False, max_length=16, unique=True, verbose_name='شناسه برنامه'),
        ),
    ]
