# Generated by Django 5.2.17 on 2026-08-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_weeklyplanitem_sequence_weeklyplanitem_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplanline',
            name='uid',
            field=models.CharField(blank=True, db_index=True, default='', help_text='شناسه ۱۴ رقمی مخصوص این نوع تولید', max_length=16, verbose_name='شناسه ردیف تولید'),
        ),
    ]
