# Generated by Django 5.2.17 on 2026-09-04 19:33

from django.db import migrations, models


def seed_params(apps, schema_editor):
    ReportParameterDef = apps.get_model("reports", "ReportParameterDef")
    defaults = [
        ("date_today", "امروز", "date", ["date", "document_date", "file_document_date", "plan_date"], "", 0),
        ("date_week_start", "ابتدای هفته", "date", ["date", "document_date", "plan_date"], "", 1),
        ("date_month_start", "ابتدای ماه", "date", ["date", "document_date", "plan_date"], "", 2),
        ("code_selected", "کد کالای انتخابی", "code", ["code", "product_code"], "", 3),
        ("qty_threshold", "آستانه تعداد", "number", ["stock_finished", "produced", "planned_qty", "actual_qty"], "0", 4),
    ]
    for code, label, kind, keys, sample, order in defaults:
        ReportParameterDef.objects.get_or_create(
            code=code,
            defaults={
                "label": label,
                "kind": kind,
                "applies_to_keys": keys,
                "sample_value": sample,
                "order": order,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0007_excel_tables_and_source_len"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportParameterDef",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=60, unique=True, verbose_name="کد پارامتر")),
                ("label", models.CharField(max_length=120, verbose_name="عنوان")),
                (
                    "kind",
                    models.CharField(
                        choices=[("date", "تاریخ"), ("code", "کد"), ("number", "عدد")],
                        default="date",
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
                ("sample_value", models.CharField(blank=True, default="", max_length=120, verbose_name="نمونه مقدار")),
                (
                    "applies_to_keys",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='مثال: ["date", "document_date", "code"]',
                        verbose_name="کلیدهای ستون مرتبط",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "پارامتر گزارش",
                "verbose_name_plural": "پارامترهای گزارش",
                "ordering": ["order", "code"],
            },
        ),
        migrations.AddField(
            model_name="savedreport",
            name="conditions",
            field=models.JSONField(blank=True, default=dict, verbose_name="شرط‌ها"),
        ),
        migrations.RunPython(seed_params, migrations.RunPython.noop),
    ]
