# Generated by Django 5.2.17 on 2026-08-09 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'گروه محصول',
                'verbose_name_plural': 'گروه\u200cهای محصول',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'گزینه نوع تولید',
                'verbose_name_plural': 'گزینه\u200cهای نوع تولید',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'واحد تولیدی',
                'verbose_name_plural': 'واحدهای تولیدی',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='StoppageReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'دلیل توقف',
                'verbose_name_plural': 'دلایل توقف',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ProductSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='catalog.productgroup')),
            ],
            options={
                'verbose_name': 'زیرگروه محصول',
                'verbose_name_plural': 'زیرگروه\u200cهای محصول',
                'ordering': ['group__order', 'order', 'name'],
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='کد')),
                ('name', models.CharField(max_length=200, verbose_name='نام قطعه')),
                ('counting_unit', models.CharField(choices=[('count', 'عدد'), ('branch', 'شاخه'), ('coil', 'کلاف'), ('meter', 'متر')], default='count', max_length=10)),
                ('needs_assembly', models.BooleanField(default=False, verbose_name='نیاز به مونتاژ')),
                ('needs_machining', models.BooleanField(default=False, verbose_name='نیاز به تراشکاری')),
                ('needs_facing', models.BooleanField(default=False, verbose_name='نیاز به کفتراشی')),
                ('per_carton', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد در کارتن')),
                ('per_bag', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد در کیسه')),
                ('depot_ceiling', models.PositiveIntegerField(blank=True, null=True, verbose_name='سقف دپو')),
                ('main_cavities', models.PositiveIntegerField(blank=True, null=True, verbose_name='حفره اصلی')),
                ('last_cycle', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='آخرین سیکل')),
                ('stock_finished', models.IntegerField(default=0, verbose_name='موجودی محصول')),
                ('stock_unassembled', models.IntegerField(default=0, verbose_name='موجودی مونتاژ\u200cنشده')),
                ('reorder_level', models.PositiveIntegerField(default=0, verbose_name='سطح سفارش مجدد')),
                ('is_active', models.BooleanField(default=True)),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productsubgroup')),
            ],
            options={
                'verbose_name': 'محصول / قطعه',
                'verbose_name_plural': 'محصولات و قطعات',
                'ordering': ['subgroup', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(choices=[('injection', 'تزریق پلاستیک'), ('extruder', 'اکسترودر لوله'), ('bling', 'بلینگ (سوکت\u200cزنی)'), ('furnace', 'کوره روکش'), ('punch_print', 'پانچ و پرینت')], default='injection', max_length=20)),
                ('number', models.CharField(help_text='شماره دستگاه یا خط', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='catalog.productionunit')),
            ],
            options={
                'verbose_name': 'دستگاه / خط',
                'verbose_name_plural': 'دستگاه\u200cها و خطوط',
                'ordering': ['unit__number', 'machine_type', 'number'],
                'unique_together': {('unit', 'machine_type', 'number')},
            },
        ),
    ]
