# Generated by Django 5.2.17 on 2026-08-09 19:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, unique=True, verbose_name='عنوان')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دلیل انحراف',
                'verbose_name_plural': 'دلایل انحراف',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit_weight_grams',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='وزن هر واحد (گرم)'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='kind',
            field=models.CharField(choices=[('fitting', 'اتصالات'), ('pipe', 'لوله')], default='fitting', max_length=10, verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('injection', 'تزریق پلاستیک'), ('extruder', 'اکسترودر لوله'), ('bling', 'بلینگ (سوکت\u200cزنی)'), ('furnace', 'کوره روکش'), ('punch_print', 'پانچ و پرینت')], default='injection', max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='number',
            field=models.CharField(help_text='شماره دستگاه یا خط', max_length=20, verbose_name='شماره'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='catalog.productionunit', verbose_name='واحد تولیدی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='counting_unit',
            field=models.CharField(choices=[('count', 'عدد'), ('branch', 'شاخه'), ('coil', 'کلاف'), ('meter', 'متر')], default='count', max_length=10, verbose_name='واحد شمارش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_cycle',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='آخرین سیکل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productsubgroup', verbose_name='زیرگروه'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='productiontypeoption',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='productiontypeoption',
            name='label',
            field=models.CharField(max_length=60, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='productiontypeoption',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='productsubgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='catalog.productgroup', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='productsubgroup',
            name='name',
            field=models.CharField(max_length=120, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='productsubgroup',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='stoppagereason',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='stoppagereason',
            name='label',
            field=models.CharField(max_length=120, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='stoppagereason',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب'),
        ),
    ]
