# Generated by Django 5.2.17 on 2026-08-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_deviationreason_product_unit_weight_grams_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramChangeReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, unique=True, verbose_name='عنوان')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دلیل تغییر برنامه',
                'verbose_name_plural': 'دلایل تغییر برنامه',
                'ordering': ['order', 'label'],
            },
        ),
    ]
